[project]
name = "prompt-viz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.52.0",
    "plotly>=5.22.0",
    "numpy>=1.26.0",
    "pyinstaller>=6.17.0",
]
